title: Intelligent Perception and Autonomous Optimization Laboratory (IPAOLab), East China University of Science and Technology
page-top-title: 
copyright-text: '&copy; IPAOLab 2026. All Rights Reserved.'
